<?php
// @codingStandardsIgnoreFile

/** @var $block \M2E\M2ECloudMagentoConnector\Block\Adminhtml\Magento\Payment\Info */
?>

<table>
    <?php
    if ($block->getPaymentMethod() != '') : ?>
        <tr>
            <td style="width: 200px;"><label><?= /* @noEscape */
                    __('Payment Method'); ?>:</label></td>
            <td><strong><?= /* @noEscape */
                    $block->escapeHtml($block->getPaymentMethod()); ?></strong></td>
        </tr>
    <?php
    endif; ?>

    <?php
    if ($block->getChannelOrderId() != '') : ?>
        <tr>
            <td style="width: 200px;"><?= /* @noEscape */
                __('Channel Order ID') ?>:
            </td>
            <td><strong><?= /* @noEscape */
                    $block->escapeHtml($block->getChannelOrderId()); ?></strong></td>
        </tr>
    <?php
    endif; ?>
</table>
